### ISSUE TITLE
Error when handling deleted expenses

### ISSUE THREAD

**Issue by alexsalomon** [juftin/lunchable-splitlunch#2]
Splitlunch is throwing an error when handling deleted expenses. 

```
> splitlunch expenses

[
  {
    "splitwise_id": 2975110000,
    "original_amount": 10.0,
    "self_paid": false,
    "financial_impact": 5.0,
    "description": "testing",
    "category": "General",
    "details": null,
    "payment": false,
    "date": "2024-02-26T23:04:06Z",
    "users": [
      84931234,
      1851234
    ],
    "created_at": "2024-02-26T23:04:22Z",
    "updated_at": "2024-02-27T00:50:57Z",
    "deleted_at": "2024-02-27T00:50:57Z",
    "deleted": true
  }
]
```
Output:

```
> splitlunch refresh --dated-after 2022-01-01

Traceback (most recent call last):
  File "/.local/bin/splitlunch", line 10, in <module>
    sys.exit(splitlunch())
             ^^^^^^^^^^^^
  File "/Library/Application Support/pipx/venvs/lunchable-splitlunch/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/pipx/venvs/lunchable-splitlunch/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Application Support/pipx/venvs/lunchable-splitlunch/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/pipx/venvs/lunchable-splitlunch/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/pipx/venvs/lunchable-splitlunch/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/pipx/venvs/lunchable-splitlunch/lib/python3.12/site-packages/lunchable_splitlunch/cli.py", line 204, in refresh_splitwise_transactions
    response = splitlunch.refresh_splitwise_transactions(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/pipx/venvs/lunchable-splitlunch/lib/python3.12/site-packages/lunchable_splitlunch/lunchmoney_splitwise.py", line 1178, in refresh_splitwise_transactions
    self.handle_deleted_transactions(deleted_transactions=deleted_transactions)
  File "/Library/Application Support/pipx/venvs/lunchable-splitlunch/lib/python3.12/site-packages/lunchable_splitlunch/lunchmoney_splitwise.py", line 1202, in handle_deleted_transactions
    notes = " || ".join(
            ^^^^^^^^^^^^
TypeError: sequence item 1: expected str instance, float found
```

**Comment by juftin** [comment]
@alexsalomon you should see this resolved now, the release should be out momentarily.
